### PR TITLE
Dijkstra's algorithm implementation

### PR DESCRIPTION
**Pull request by sergey-kintsel**
- [ ] add more tests
- [ ] maybe use something better than Float::Infinity (maybe something that responds on `:>` always with a true)
- [ ] improve performance

### CODE REVIEW

**Comment by dfyx** [comment]
I think you can return as soon as you insert the destination node inti `@visited_nodes`

**Comment by sergey-kintsel** [comment]
@dfyx I am not sure.. look at this picture. 

we need to get from 1 to 2 node. first we are adding 2 and 3 into array to be gone though. then we take 2nd, set everything for 4 node and set 2nd as visited. but for 2 we have path length equals 10, instead of 3 as we would go using 3rd and 4th nodes

**Comment by dfyx** [comment]
What you're describing is a BFS, not Dijkstra's Algorithm which would visit the nodes in the following order: [1, 3, 4, 2].

**Comment by dirkholzapfel** [comment]
Thanks for your PR - I will review this weekend.

**Comment by dirkholzapfel** [comment]
Hey @sergey-kintsel. I merged "Fix RuboCop offences	fd356e2" - thanks a lot for that!
Regarding Dijkstra I agree with @dfyx - your code does not implement Dijkstra algorithm. 

I started to work on an implementation today and will release it within the next week. 
Cheers, Dirk

**Pull request closed without merging**
